### ISSUE TITLE
roadmap?

### ISSUE THREAD

**Issue by HaveF** [MinJieLiu/egg-graphql-apollo#1]
我是从一个issue跟到这个repo来
看上去好像不错，但还没有试

请问对于此repo你有什么未来计划吗？或者维护有没有什么大概想法？

我担心如果是个临时性的项目，后期维护可能会比较头疼

谢谢！

**Comment by MinJieLiu** [comment]
@HaveF 其实最开始我也担心这个问题，不是官方维护的后期可能会很头疼，但是从事情的缓急程度上来看是很必要的。

我的目的很明确，用它来更好的写 `graphql`，至少我现在用起来感觉还不错。我另外一个博客项目就用它（还在开发阶段）。后面我会跟紧官方的库，或可能有新的想法让它变得更好。

**Comment by HaveF** [comment]
再出一个egg-graphql --> egg-graphql-apollo 迁移说明是不是更好？

**Comment by MinJieLiu** [comment]
可以考虑出一个
